name: biobb_wf_haddock
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_haddock==5.2.0
  - biobb_pdb_tools==5.2.0
  - biobb_io==5.2.0
  - nglview
  - ipywidgets
  - jupyter
  - ambertools # For pytraj
